
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENTIFIER NUMBER OPERATOR RESERVED SEPARATORprogram : statement_liststatement_list : statement\n| statement statement_liststatement : RESERVED IDENTIFIER OPERATOR NUMBER SEPARATORstatement : IDENTIFIER OPERATOR IDENTIFIER OPERATOR NUMBER SEPARATOR\n| IDENTIFIER OPERATOR IDENTIFIER OPERATOR IDENTIFIER SEPARATOR\n| IDENTIFIER OPERATOR NUMBER SEPARATORstatement : RESERVED SEPARATOR expression SEPARATOR block\n| RESERVED SEPARATOR expression SEPARATOR block RESERVED block\n| RESERVED SEPARATOR expression SEPARATOR block RESERVED statementblock : SEPARATOR statement_list SEPARATOR\n| SEPARATOR SEPARATORexpression : IDENTIFIER comparison_operator IDENTIFIER\n| IDENTIFIER comparison_operator NUMBERcomparison_operator : OPERATOR'
    
_lr_action_items = {'RESERVED':([0,3,20,21,22,23,28,30,31,32,33,34,35,],[4,4,-7,-4,4,30,-12,4,-6,-5,-11,-9,-10,]),'IDENTIFIER':([0,3,4,8,9,17,18,19,20,21,22,23,28,30,31,32,33,34,35,],[5,5,7,12,13,24,-15,26,-7,-4,5,-8,-12,5,-6,-5,-11,-9,-10,]),'$end':([1,2,3,6,20,21,23,28,31,32,33,34,35,],[0,-1,-2,-3,-7,-4,-8,-12,-6,-5,-11,-9,-10,]),'SEPARATOR':([3,4,6,11,14,15,16,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,],[-2,8,-3,16,20,21,22,-7,-4,28,-8,-13,-14,31,32,-12,33,22,-6,-5,-11,-9,-10,]),'OPERATOR':([5,7,12,13,],[9,10,18,19,]),'NUMBER':([9,10,17,18,19,],[14,15,25,-15,27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,3,22,],[2,6,29,]),'statement':([0,3,22,30,],[3,3,3,35,]),'expression':([8,],[11,]),'comparison_operator':([12,],[17,]),'block':([16,30,],[23,34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','BrunnoLuiz_Analisador.py',54),
  ('statement_list -> statement','statement_list',1,'p_statement_list','BrunnoLuiz_Analisador.py',60),
  ('statement_list -> statement statement_list','statement_list',2,'p_statement_list','BrunnoLuiz_Analisador.py',61),
  ('statement -> RESERVED IDENTIFIER OPERATOR NUMBER SEPARATOR','statement',5,'p_statement_declaration','BrunnoLuiz_Analisador.py',65),
  ('statement -> IDENTIFIER OPERATOR IDENTIFIER OPERATOR NUMBER SEPARATOR','statement',6,'p_statement_assignment','BrunnoLuiz_Analisador.py',69),
  ('statement -> IDENTIFIER OPERATOR IDENTIFIER OPERATOR IDENTIFIER SEPARATOR','statement',6,'p_statement_assignment','BrunnoLuiz_Analisador.py',70),
  ('statement -> IDENTIFIER OPERATOR NUMBER SEPARATOR','statement',4,'p_statement_assignment','BrunnoLuiz_Analisador.py',71),
  ('statement -> RESERVED SEPARATOR expression SEPARATOR block','statement',5,'p_statement_condition','BrunnoLuiz_Analisador.py',76),
  ('statement -> RESERVED SEPARATOR expression SEPARATOR block RESERVED block','statement',7,'p_statement_condition','BrunnoLuiz_Analisador.py',77),
  ('statement -> RESERVED SEPARATOR expression SEPARATOR block RESERVED statement','statement',7,'p_statement_condition','BrunnoLuiz_Analisador.py',78),
  ('block -> SEPARATOR statement_list SEPARATOR','block',3,'p_block','BrunnoLuiz_Analisador.py',84),
  ('block -> SEPARATOR SEPARATOR','block',2,'p_block','BrunnoLuiz_Analisador.py',85),
  ('expression -> IDENTIFIER comparison_operator IDENTIFIER','expression',3,'p_expression_comparison','BrunnoLuiz_Analisador.py',89),
  ('expression -> IDENTIFIER comparison_operator NUMBER','expression',3,'p_expression_comparison','BrunnoLuiz_Analisador.py',90),
  ('comparison_operator -> OPERATOR','comparison_operator',1,'p_comparison_operator','BrunnoLuiz_Analisador.py',94),
]
